language: python

services:
  - docker

python:
  - "3.7"

before_install:
  - cd deployment
  - pip install -r requirements.txt
  - export TAG=${TRAVIS_BRANCH}-${TRAVIS_COMMIT:0:7}
  - ansible-playbook dockerhub.yaml -vv
  - docker images

install:
  - echo 0

script:
  - echo 0

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    repo: StateArchivesOfNorthCarolina/ratom-server
    all_branches: true