language: python

services:
  - docker

python:
  - "3.7"

env:
  - DJANGO_SECRET_KEY='asldjklkakjsdlkjadsinjaidnlkasdf'

before_install:
  - docker build --build-arg DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY -t govsanc/ratom-server .

install:
  - pip install -r requirements/base.txt

script:
  - echo 0

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    repo: StateArchivesOfNorthCarolina/ratom-server
    all_branches: true