language: python

services:
  - docker

python:
  - "3.7"

env:
  - SECRET_KEY='asldjklkakjsdlkjadsinjaidnlkasdf'

before_install:
  - docker build --build-arg SECRET_KEY=$SECRET_KEY -t govsanc/ratom-server .

install:
  - pip install -r requirements/base.txt

script:
  - python manage.py test

deploy:
  provider: script
  script: bash docker_push.sh