language: python

services:
  - docker

python:
  - "3.7"

before_install:
  - docker build -t govsanc/ratom-server .

install:
  - pip install -r requirements/base.txt

script:
  - python manage.py test

deploy:
  provider: script
  script: bash docker_push.sh