language: python

cache: pip

services:
  - docker

python:
  - "3.7"

env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - DOCKERHUB_REPO=govsanc/ratom-server

install:
  - pip install -r deployment/requirements.txt

before_script:
  # Build container for this commit before tests run
  - make build-base
  - make build-test

script:
  # - make ci-pre-commit
  - make ci-test

before_deploy:
  # Build deploy image
  - make build-deploy
  - docker images
  # Install kubectl using Google SDK
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components install kubectl

deploy:
  provider: script
  script: bash deployment/ci_deployment.sh
  on:
    repo: StateArchivesOfNorthCarolina/ratom-server
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(develop|master)$
