language: python

cache: pip

services:
  - docker

python:
  - "3.7"

env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - DOCKERHUB_REPO=govsanc/ratom-server

before_install:
  # Upgrade Docker to latest version that supports Docker Build enhancements
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version
  - docker pull python:3.7-slim

install:
  - pip install -r deployment/requirements.txt

before_script:
  # Build container for this commit before tests run
  - make build-base
  - make build-test

script:
  - make ci-pre-commit
  - make ci-test
  # - docker-compose up -d
  # - docker-compose exec db /bin/bash -c "until psql -l; do echo 'db unavailable. sleeping'; sleep 1; done"
  # - docker-compose exec app /bin/bash -c "code/python manage.py test"

before_deploy:
  # Build deploy image
  - make build-deploy
  - docker images
  # Install kubectl using Google SDK
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components install kubectl

deploy:
  provider: script
  script: bash deployment/ci_deployment.sh
  on:
    repo: StateArchivesOfNorthCarolina/ratom-server
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(develop|master)$
