language: python

services:
  - docker

python:
  - "3.7"

before_install:
  - cd deployment
  - pip install -r requirements.txt

install:
  - pip install -r requirements/base.txt

script:
  - docker run -it govsanc/ratom-server /code/python manage.py test

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    repo: StateArchivesOfNorthCarolina/ratom-server
    all_branches: true