version: '3.4'
volumes:
    dev_ratom_server_data: {}

services:
  cache:
    restart: always
    image: memcached:1.5
    expose:
      - "11211"
  db:
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: ratom_server
      DATABASE_URL: postgres://postgres@127.0.0.1/ratom_server
    restart: always
    image: postgres:14-alpine
    ports:
      - "54327:5432"
    volumes:
      - dev_ratom_server_data:/var/lib/postgresql/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"
