---

ansible_connection: local
k8s_namespace: "ratom-{{ env_name }}"

# App
k8s_container_name: api
k8s_container_image: govsanc/ratom-server
k8s_container_image_tag: latest
k8s_container_port: 8000
k8s_container_ingress_paths:
- /admin
- /api
- /django-static

# Redis
k8s_redis_enabled: true
k8s_elasticsearch_enabled: true

# Celery
k8s_worker_enabled: true
k8s_worker_celery_app: "ratom"
# Bump worker resources to handle large file imports
k8s_worker_resources:
  requests:
    memory: "768Mi"
    cpu: "250m"

# Celery beat
k8s_worker_beat_enabled: false
